package VIEW;

import CONTROLLER.MenuController;
import MODEL.ContaModel;
import java.awt.Cursor;

/**
 *
 * @author Aluno
 */

public class MenuView extends javax.swing.JFrame {
          
    /**
     * Creates new form Menu
     */
        
    public MenuView() {
        initComponents();
        MenuController menuC = new MenuController(this);
        menuC.iniciar();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblContas = new javax.swing.JLabel();
        lblObito = new javax.swing.JLabel();
        lblPagamentos = new javax.swing.JLabel();
        lblEstoque = new javax.swing.JLabel();
        lblEmprestimo = new javax.swing.JLabel();
        lblImagemMenu = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblLogado = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuAcesso = new javax.swing.JMenu();
        menuEmpresa = new javax.swing.JMenu();
        menuFornecedores = new javax.swing.JMenu();
        menuFuncionarios = new javax.swing.JMenu();
        menuMateriais = new javax.swing.JMenu();
        menuPlanos = new javax.swing.JMenu();
        menuRelatorios = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem6 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem7 = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblContas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblContasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblContasMouseEntered(evt);
            }
        });
        jPanel1.add(lblContas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 130, 110));

        lblObito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblObitoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblObitoMouseEntered(evt);
            }
        });
        jPanel1.add(lblObito, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 130, 110));

        lblPagamentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPagamentosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblPagamentosMouseEntered(evt);
            }
        });
        jPanel1.add(lblPagamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 150, 110));

        lblEstoque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEstoqueMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblEstoqueMouseEntered(evt);
            }
        });
        jPanel1.add(lblEstoque, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 140, 110));

        lblEmprestimo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEmprestimoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblEmprestimoMouseEntered(evt);
            }
        });
        jPanel1.add(lblEmprestimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 0, 150, 110));

        lblImagemMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IBAGENS/menu.png"))); // NOI18N
        jPanel1.add(lblImagemMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IBAGENS/logo.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IBAGENS/logo.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, -1, -1));

        lblLogado.setText("Usuário Logado:");

        lblUsuario.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblUsuario.setText("lblUsuario");

        menuBar.setPreferredSize(new java.awt.Dimension(415, 31));

        menuAcesso.setText("Acesso");
        menuAcesso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuAcessoMouseClicked(evt);
            }
        });
        menuBar.add(menuAcesso);

        menuEmpresa.setText("Empresa");
        menuEmpresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuEmpresaMouseClicked(evt);
            }
        });
        menuBar.add(menuEmpresa);

        menuFornecedores.setText("Fornecedores");
        menuFornecedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuFornecedoresMouseClicked(evt);
            }
        });
        menuBar.add(menuFornecedores);

        menuFuncionarios.setText("Funcionários");
        menuFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuFuncionariosMouseClicked(evt);
            }
        });
        menuBar.add(menuFuncionarios);

        menuMateriais.setText("Materiais");
        menuMateriais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMateriaisMouseClicked(evt);
            }
        });
        menuBar.add(menuMateriais);

        menuPlanos.setText("Planos");
        menuPlanos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuPlanosMouseClicked(evt);
            }
        });
        menuBar.add(menuPlanos);

        menuRelatorios.setText("Relatórios");

        jMenuItem2.setText("Contas em Débito");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuRelatorios.add(jMenuItem2);
        menuRelatorios.add(jSeparator1);

        jMenuItem5.setText("Materiais em Estoque");
        menuRelatorios.add(jMenuItem5);
        menuRelatorios.add(jSeparator2);

        jMenuItem6.setText("Materiais Emprestados");
        menuRelatorios.add(jMenuItem6);
        menuRelatorios.add(jSeparator3);

        jMenuItem7.setText("Óbitos");
        menuRelatorios.add(jMenuItem7);

        menuBar.add(menuRelatorios);

        menuSair.setText("Sair");
        menuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSairMouseClicked(evt);
            }
        });
        menuBar.add(menuSair);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 812, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsuario)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLogado)
                    .addComponent(lblUsuario))
                .addGap(0, 7, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuEmpresaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuEmpresaMouseClicked
        
        EmpresaView empresaV = new EmpresaView();
        empresaV.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuEmpresaMouseClicked

    private void menuFornecedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuFornecedoresMouseClicked
       
        FornecedorView fornV = new FornecedorView();
        fornV.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuFornecedoresMouseClicked

    private void menuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSairMouseClicked
        
        LoginView loginV = new LoginView();
        loginV.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuSairMouseClicked

    private void menuFuncionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuFuncionariosMouseClicked
        
        FuncionariosView funcV = new FuncionariosView();
        funcV.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuFuncionariosMouseClicked

    private void menuMateriaisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMateriaisMouseClicked
        
        MaterialView mateV = new MaterialView();
        mateV.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuMateriaisMouseClicked

    private void menuPlanosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPlanosMouseClicked
        
        PlanosView planoV = new PlanosView();
        planoV.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuPlanosMouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void menuAcessoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAcessoMouseClicked
        
        AcessoView acessoV = new AcessoView();
        acessoV.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuAcessoMouseClicked

    private void lblContasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblContasMouseClicked
        
        ContaModel contaM = new ContaModel();
        ContaView contasV = new ContaView(contaM);
        contasV.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblContasMouseClicked

    private void lblContasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblContasMouseEntered
        
        lblContas.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lblContasMouseEntered

    private void lblObitoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblObitoMouseEntered
        
        lblObito.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lblObitoMouseEntered

    private void lblPagamentosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPagamentosMouseEntered
        
        lblPagamentos.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lblPagamentosMouseEntered

    private void lblEstoqueMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEstoqueMouseEntered
        
        lblEstoque.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lblEstoqueMouseEntered

    private void lblEmprestimoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEmprestimoMouseEntered
        
        lblEmprestimo.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lblEmprestimoMouseEntered

    private void lblObitoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblObitoMouseClicked
        
        ObitosView obitosV = new ObitosView();
        obitosV.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblObitoMouseClicked

    private void lblPagamentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPagamentosMouseClicked
        
        PesqMensalidadeView mensalV = new PesqMensalidadeView();
        mensalV.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblPagamentosMouseClicked

    private void lblEstoqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEstoqueMouseClicked
        
        ControleEstoqueView estoqueV = new ControleEstoqueView();
        estoqueV.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblEstoqueMouseClicked

    private void lblEmprestimoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEmprestimoMouseClicked
        
        EmprestimoView emprestV = new EmprestimoView();
        emprestV.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblEmprestimoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    public javax.swing.JLabel lblContas;
    public javax.swing.JLabel lblEmprestimo;
    public javax.swing.JLabel lblEstoque;
    private javax.swing.JLabel lblImagemMenu;
    private javax.swing.JLabel lblLogado;
    public javax.swing.JLabel lblObito;
    public javax.swing.JLabel lblPagamentos;
    public javax.swing.JLabel lblUsuario;
    public javax.swing.JMenu menuAcesso;
    public javax.swing.JMenuBar menuBar;
    public javax.swing.JMenu menuEmpresa;
    public javax.swing.JMenu menuFornecedores;
    public javax.swing.JMenu menuFuncionarios;
    public javax.swing.JMenu menuMateriais;
    public javax.swing.JMenu menuPlanos;
    public javax.swing.JMenu menuRelatorios;
    public javax.swing.JMenu menuSair;
    // End of variables declaration//GEN-END:variables
}
