/**
 *
 * @author Aluno
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblContas = new javax.swing.JLabel();
        lblObito = new javax.swing.JLabel();
        lblPagamentos = new javax.swing.JLabel();
        lblEstoque = new javax.swing.JLabel();
        lblEmprestimo = new javax.swing.JLabel();
        lblImagemMenu = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuEmpresa = new javax.swing.JMenu();
        menuFornecedores = new javax.swing.JMenu();
        menuFuncionarios = new javax.swing.JMenu();
        menuMateriais = new javax.swing.JMenu();
        menuPlanos = new javax.swing.JMenu();
        menuRelatorios = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem6 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem7 = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(lblContas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 130, 110));
        jPanel1.add(lblObito, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 130, 110));
        jPanel1.add(lblPagamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 150, 110));
        jPanel1.add(lblEstoque, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 140, 110));
        jPanel1.add(lblEmprestimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 0, 150, 110));

        lblImagemMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IBAGENS/menu.png"))); // NOI18N
        jPanel1.add(lblImagemMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IBAGENS/logo.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jMenuBar1.setPreferredSize(new java.awt.Dimension(415, 31));

        menuEmpresa.setText("Empresa");
        menuEmpresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuEmpresaMouseClicked(evt);
            }
        });
        menuEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEmpresaActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuEmpresa);

        menuFornecedores.setText("Fornecedores");
        menuFornecedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuFornecedoresMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuFornecedores);

        menuFuncionarios.setText("Funcionários");
        menuFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuFuncionariosMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuFuncionarios);

        menuMateriais.setText("Materiais");
        menuMateriais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMateriaisMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuMateriais);

        menuPlanos.setText("Planos");
        menuPlanos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuPlanosMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuPlanos);

        menuRelatorios.setText("Relatórios");

        jMenuItem2.setText("Contas em Débito");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuRelatorios.add(jMenuItem2);
        menuRelatorios.add(jSeparator1);

        jMenuItem5.setText("Materiais em Estoque");
        menuRelatorios.add(jMenuItem5);
        menuRelatorios.add(jSeparator2);

        jMenuItem6.setText("Materiais Emprestados");
        menuRelatorios.add(jMenuItem6);
        menuRelatorios.add(jSeparator3);

        jMenuItem7.setText("Óbitos");
        menuRelatorios.add(jMenuItem7);

        jMenuBar1.add(menuRelatorios);

        menuSair.setText("Sair");
        menuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSairMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 812, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 35, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEmpresaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_menuEmpresaActionPerformed

    private void menuEmpresaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuEmpresaMouseClicked
        
        Empresa tela = new Empresa();
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuEmpresaMouseClicked

    private void menuFornecedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuFornecedoresMouseClicked
       
        Fornecedores tela = new Fornecedores();
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuFornecedoresMouseClicked

    private void menuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSairMouseClicked
        
        Login tela = new Login();
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuSairMouseClicked

    private void menuFuncionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuFuncionariosMouseClicked
        
        Funcionarios tela = new Funcionarios();
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuFuncionariosMouseClicked

    private void menuMateriaisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMateriaisMouseClicked
        
        Materiais tela = new Materiais();
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuMateriaisMouseClicked

    private void menuPlanosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPlanosMouseClicked
        
        Planos tela = new Planos();
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuPlanosMouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JLabel lblContas;
    private javax.swing.JLabel lblEmprestimo;
    private javax.swing.JLabel lblEstoque;
    private javax.swing.JLabel lblImagemMenu;
    private javax.swing.JLabel lblObito;
    private javax.swing.JLabel lblPagamentos;
    private javax.swing.JMenu menuEmpresa;
    private javax.swing.JMenu menuFornecedores;
    private javax.swing.JMenu menuFuncionarios;
    private javax.swing.JMenu menuMateriais;
    private javax.swing.JMenu menuPlanos;
    private javax.swing.JMenu menuRelatorios;
    private javax.swing.JMenu menuSair;
    // End of variables declaration//GEN-END:variables
}
